package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestLoadGroupPre extends Request<ResponseLoadGroupPre> {

    public static final int HEADER = 0x24;

    public static RequestLoadGroupPre fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestLoadGroupPre(), data);
    }

    private int groupPreId;

    public RequestLoadGroupPre(int groupPreId) {
        this.groupPreId = groupPreId;
    }

    public RequestLoadGroupPre() {

    }

    public int getGroupPreId() {
        return this.groupPreId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupPreId = values.getInt(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.groupPreId);
    }

    @Override
    public String toString() {
        String res = "rpc LoadGroupPre{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
