package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import im.actor.core.api.*;

public class RequestUpdateRestrictedDomains extends Request<ResponseVoid> {

    public static final int HEADER = 0x535;
    public static RequestUpdateRestrictedDomains fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestUpdateRestrictedDomains(), data);
    }

    private ApiGroupOutPeer groupPeer;
    private String domains;

    public RequestUpdateRestrictedDomains(@NotNull ApiGroupOutPeer groupPeer, @NotNull String domains) {
        this.groupPeer = groupPeer;
        this.domains = domains;
    }

    public RequestUpdateRestrictedDomains() {

    }

    @NotNull
    public ApiGroupOutPeer getGroupPeer() {
        return this.groupPeer;
    }

    @NotNull
    public String getDomains() {
        return this.domains;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupPeer = values.getObj(1, new ApiGroupOutPeer());
        this.domains = values.getString(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.groupPeer == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.groupPeer);
        if (this.domains == null) {
            throw new IOException();
        }
        writer.writeString(2, this.domains);
    }

    @Override
    public String toString() {
        String res = "rpc UpdateRestrictedDomains{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
