package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import im.actor.core.api.*;

public class RequestStartPhoneAuth extends Request<ResponseStartPhoneAuth> {

    public static final int HEADER = 0xbf;
    public static RequestStartPhoneAuth fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestStartPhoneAuth(), data);
    }

    private long phoneNumber;
    private int appId;
    private String apiKey;
    private byte[] deviceHash;
    private String deviceTitle;
    private String deviceIpAddress;
    private String deviceLocation;
    private String deviceOS;
    private String systemName;
    private String timeZone;
    private List<String> preferredLanguages;

    public RequestStartPhoneAuth(long phoneNumber, int appId, @NotNull String apiKey, @NotNull byte[] deviceHash, @NotNull String deviceTitle, @NotNull String deviceIpAddress, @NotNull String deviceLocation, @NotNull String deviceOS, @NotNull String systemName, @Nullable String timeZone, @NotNull List<String> preferredLanguages) {
        this.phoneNumber = phoneNumber;
        this.appId = appId;
        this.apiKey = apiKey;
        this.deviceHash = deviceHash;
        this.deviceTitle = deviceTitle;
        this.deviceIpAddress = deviceIpAddress;
        this.deviceLocation = deviceLocation;
        this.deviceOS = deviceOS;
        this.systemName = systemName;
        this.timeZone = timeZone;
        this.preferredLanguages = preferredLanguages;
    }

    public RequestStartPhoneAuth() {

    }

    public long getPhoneNumber() {
        return this.phoneNumber;
    }

    public int getAppId() {
        return this.appId;
    }

    @NotNull
    public String getApiKey() {
        return this.apiKey;
    }

    @NotNull
    public byte[] getDeviceHash() {
        return this.deviceHash;
    }

    @NotNull
    public String getDeviceTitle() {
        return this.deviceTitle;
    }

    @NotNull
    public String getDeviceIpAddress() {
        return this.deviceIpAddress;
    }

    @NotNull
    public String getDeviceLocation() {
        return this.deviceLocation;
    }

    @NotNull
    public String getDeviceOS() {
        return this.deviceOS;
    }

    @NotNull
    public String getSystemName() {
        return this.systemName;
    }

    @Nullable
    public String getTimeZone() {
        return this.timeZone;
    }

    @NotNull
    public List<String> getPreferredLanguages() {
        return this.preferredLanguages;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.phoneNumber = values.getLong(1);
        this.appId = values.getInt(2);
        this.apiKey = values.getString(3);
        this.deviceHash = values.getBytes(4);
        this.deviceTitle = values.getString(5);
        this.deviceIpAddress = values.getString(6);
        this.deviceLocation = values.getString(7);
        this.deviceOS = values.getString(8);
        this.systemName = values.getString(9);
        this.timeZone = values.optString(10);
        this.preferredLanguages = values.getRepeatedString(11);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.phoneNumber);
        writer.writeInt(2, this.appId);
        if (this.apiKey == null) {
            throw new IOException();
        }
        writer.writeString(3, this.apiKey);
        if (this.deviceHash == null) {
            throw new IOException();
        }
        writer.writeBytes(4, this.deviceHash);
        if (this.deviceTitle == null) {
            throw new IOException();
        }
        writer.writeString(5, this.deviceTitle);
        if (this.deviceIpAddress == null) {
            throw new IOException();
        }
        writer.writeString(6, this.deviceIpAddress);
        if (this.deviceLocation == null) {
            throw new IOException();
        }
        writer.writeString(7, this.deviceLocation);
        if (this.deviceOS == null) {
            throw new IOException();
        }
        writer.writeString(8, this.deviceOS);
        if (this.systemName == null) {
            throw new IOException();
        }
        writer.writeString(9, this.systemName);
        if (this.timeZone != null) {
            writer.writeString(10, this.timeZone);
        }
        writer.writeRepeatedString(11, this.preferredLanguages);
    }

    @Override
    public String toString() {
        String res = "rpc StartPhoneAuth{";
        res += "phoneNumber=" + this.phoneNumber;
        res += ", deviceHash=" + byteArrayToString(this.deviceHash);
        res += ", deviceTitle=" + this.deviceTitle;
        res += ", deviceIpAddress=" + this.deviceIpAddress;
        res += ", deviceLocation=" + this.deviceLocation;
        res += ", deviceOS=" + this.deviceOS;
        res += ", systemName=" + this.systemName;
        res += ", timeZone=" + this.timeZone;
        res += ", preferredLanguages=" + this.preferredLanguages;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
