package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Request;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class RequestChangeOrder extends Request<ResponseSeq> {

    public static final int HEADER = 0x23;

    public static RequestChangeOrder fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestChangeOrder(), data);
    }

    private int fromGroupId;
    private int toGroupId;

    public RequestChangeOrder(int fromGroupId, int toGroupId) {
        this.fromGroupId = fromGroupId;
        this.toGroupId = toGroupId;
    }

    public RequestChangeOrder() {

    }

    public int getFromGroupId() {
        return this.fromGroupId;
    }

    public int getToGroupId() {
        return this.toGroupId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.fromGroupId = values.getInt(1);
        this.toGroupId = values.getInt(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.fromGroupId);
        writer.writeInt(2, this.toGroupId);
    }

    @Override
    public String toString() {
        String res = "rpc ChangeOrder{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
