package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

import im.actor.core.api.ApiGroupPre;
import im.actor.core.network.parser.Response;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class ResponseLoadGroupPre extends Response {

    public static final int HEADER = 0x15;

    public static ResponseLoadGroupPre fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseLoadGroupPre(), data);
    }

    private ApiGroupPre groupPre;

    public ResponseLoadGroupPre(@NotNull ApiGroupPre groupPre) {
        this.groupPre = groupPre;
    }

    public ResponseLoadGroupPre() {

    }

    @NotNull
    public ApiGroupPre getGroupPre() {
        return this.groupPre;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupPre = values.getObj(1, new ApiGroupPre());
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.groupPre == null) {
            throw new IOException();
        }
        writer.writeObject(1, this.groupPre);
    }

    @Override
    public String toString() {
        String res = "tuple LoadGroupPre{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
