package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateResetGroupPre extends Update {

    public static final int HEADER = 0x60;

    public static UpdateResetGroupPre fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateResetGroupPre(), data);
    }

    private long resetDate;

    public UpdateResetGroupPre(long resetDate) {
        this.resetDate = resetDate;
    }

    public UpdateResetGroupPre() {

    }

    public long getResetDate() {
        return this.resetDate;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.resetDate = values.getLong(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.resetDate);
    }

    @Override
    public String toString() {
        String res = "update ResetGroupPre{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
