package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import im.actor.core.api.*;

public class UpdateRestrictedDomainsChanged extends Update {

    public static final int HEADER = 0x874;
    public static UpdateRestrictedDomainsChanged fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateRestrictedDomainsChanged(), data);
    }

    private int groupId;
    private String domains;

    public UpdateRestrictedDomainsChanged(int groupId, @NotNull String domains) {
        this.groupId = groupId;
        this.domains = domains;
    }

    public UpdateRestrictedDomainsChanged() {

    }

    public int getGroupId() {
        return this.groupId;
    }

    @NotNull
    public String getDomains() {
        return this.domains;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupId = values.getInt(1);
        this.domains = values.getString(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.groupId);
        if (this.domains == null) {
            throw new IOException();
        }
        writer.writeString(2, this.domains);
    }

    @Override
    public String toString() {
        String res = "update RestrictedDomainsChanged{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
