package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import im.actor.core.api.*;

public class UpdateResetGroupPre extends Update {

    public static final int HEADER = 0x60;
    public static UpdateResetGroupPre fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateResetGroupPre(), data);
    }

    private long resetDate;

    public UpdateResetGroupPre(long resetDate) {
        this.resetDate = resetDate;
    }

    public UpdateResetGroupPre() {

    }

    public long getResetDate() {
        return this.resetDate;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.resetDate = values.getLong(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeLong(1, this.resetDate);
    }

    @Override
    public String toString() {
        String res = "update ResetGroupPre{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
