package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import im.actor.core.api.*;

public class UpdateGroupPreOrderChanged extends Update {

    public static final int HEADER = 0x59;
    public static UpdateGroupPreOrderChanged fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateGroupPreOrderChanged(), data);
    }

    private int fromGroupId;
    private int fromOrder;
    private int toGroupId;
    private int toOrder;

    public UpdateGroupPreOrderChanged(int fromGroupId, int fromOrder, int toGroupId, int toOrder) {
        this.fromGroupId = fromGroupId;
        this.fromOrder = fromOrder;
        this.toGroupId = toGroupId;
        this.toOrder = toOrder;
    }

    public UpdateGroupPreOrderChanged() {

    }

    public int getFromGroupId() {
        return this.fromGroupId;
    }

    public int getFromOrder() {
        return this.fromOrder;
    }

    public int getToGroupId() {
        return this.toGroupId;
    }

    public int getToOrder() {
        return this.toOrder;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.fromGroupId = values.getInt(1);
        this.fromOrder = values.getInt(2);
        this.toGroupId = values.getInt(3);
        this.toOrder = values.getInt(4);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.fromGroupId);
        writer.writeInt(2, this.fromOrder);
        writer.writeInt(3, this.toGroupId);
        writer.writeInt(4, this.toOrder);
    }

    @Override
    public String toString() {
        String res = "update GroupPreOrderChanged{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
