package im.actor.core.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

import im.actor.core.network.parser.Update;
import im.actor.runtime.bser.Bser;
import im.actor.runtime.bser.BserValues;
import im.actor.runtime.bser.BserWriter;

public class UpdateGroupPreParentChanged extends Update {

    public static final int HEADER = 0x58;

    public static UpdateGroupPreParentChanged fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateGroupPreParentChanged(), data);
    }

    private int groupId;
    private int parentId;
    private int oldParentId;

    public UpdateGroupPreParentChanged(int groupId, int parentId, int oldParentId) {
        this.groupId = groupId;
        this.parentId = parentId;
        this.oldParentId = oldParentId;
    }

    public UpdateGroupPreParentChanged() {

    }

    public int getGroupId() {
        return this.groupId;
    }

    public int getParentId() {
        return this.parentId;
    }

    public int getOldParentId() {
        return this.oldParentId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.groupId = values.getInt(1);
        this.parentId = values.getInt(2);
        this.oldParentId = values.getInt(3);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.groupId);
        writer.writeInt(2, this.parentId);
        writer.writeInt(3, this.oldParentId);
    }

    @Override
    public String toString() {
        String res = "update GroupPreParentChanged{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
