package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;

public class ApiAuthSession extends BserObject {

    private int id;
    private ApiAuthHolder authHolder;
    private int appId;
    private String appTitle;
    private String deviceTitle;
    private String deviceIpAddress;
    private String deviceLocation;
    private String deviceOSVersion;
    private int authTime;
    private String authLocation;
    private Double latitude;
    private Double longitude;

    public ApiAuthSession(int id, @NotNull ApiAuthHolder authHolder, int appId, @NotNull String appTitle, @NotNull String deviceTitle, @NotNull String deviceIpAddress, @NotNull String deviceLocation, @NotNull String deviceOSVersion, int authTime, @NotNull String authLocation, @Nullable Double latitude, @Nullable Double longitude) {
        this.id = id;
        this.authHolder = authHolder;
        this.appId = appId;
        this.appTitle = appTitle;
        this.deviceTitle = deviceTitle;
        this.deviceIpAddress = deviceIpAddress;
        this.deviceLocation = deviceLocation;
        this.deviceOSVersion = deviceOSVersion;
        this.authTime = authTime;
        this.authLocation = authLocation;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public ApiAuthSession() {

    }

    public int getId() {
        return this.id;
    }

    @NotNull
    public ApiAuthHolder getAuthHolder() {
        return this.authHolder;
    }

    public int getAppId() {
        return this.appId;
    }

    @NotNull
    public String getAppTitle() {
        return this.appTitle;
    }

    @NotNull
    public String getDeviceTitle() {
        return this.deviceTitle;
    }

    @NotNull
    public String getDeviceIpAddress() {
        return this.deviceIpAddress;
    }

    @NotNull
    public String getDeviceLocation() {
        return this.deviceLocation;
    }

    @NotNull
    public String getDeviceOSVersion() {
        return this.deviceOSVersion;
    }

    public int getAuthTime() {
        return this.authTime;
    }

    @NotNull
    public String getAuthLocation() {
        return this.authLocation;
    }

    @Nullable
    public Double getLatitude() {
        return this.latitude;
    }

    @Nullable
    public Double getLongitude() {
        return this.longitude;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.id = values.getInt(1);
        this.authHolder = ApiAuthHolder.parse(values.getInt(2));
        this.appId = values.getInt(3);
        this.appTitle = values.getString(4);
        this.deviceTitle = values.getString(5);
        this.deviceIpAddress = values.getString(6);
        this.deviceLocation = values.getString(7);
        this.deviceOSVersion = values.getString(8);
        this.authTime = values.getInt(9);
        this.authLocation = values.getString(10);
        this.latitude = values.optDouble(11);
        this.longitude = values.optDouble(12);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.id);
        if (this.authHolder == null) {
            throw new IOException();
        }
        writer.writeInt(2, this.authHolder.getValue());
        writer.writeInt(3, this.appId);
        if (this.appTitle == null) {
            throw new IOException();
        }
        writer.writeString(4, this.appTitle);
        if (this.deviceTitle == null) {
            throw new IOException();
        }
        writer.writeString(5, this.deviceTitle);
        if (this.deviceIpAddress == null) {
            throw new IOException();
        }
        writer.writeString(6, this.deviceIpAddress);
        if (this.deviceLocation == null) {
            throw new IOException();
        }
        writer.writeString(7, this.deviceLocation);
        if (this.deviceOSVersion == null) {
            throw new IOException();
        }
        writer.writeString(8, this.deviceOSVersion);
        writer.writeInt(9, this.authTime);
        if (this.authLocation == null) {
            throw new IOException();
        }
        writer.writeString(10, this.authLocation);
        if (this.latitude != null) {
            writer.writeDouble(11, this.latitude);
        }
        if (this.longitude != null) {
            writer.writeDouble(12, this.longitude);
        }
    }

    @Override
    public String toString() {
        String res = "struct AuthSession{";
        res += "id=" + this.id;
        res += ", authHolder=" + this.authHolder;
        res += ", appId=" + this.appId;
        res += ", appTitle=" + this.appTitle;
        res += ", deviceTitle=" + this.deviceTitle;
        res += ", deviceIpAddress=" + this.deviceIpAddress;
        res += ", deviceLocation=" + this.deviceLocation;
        res += ", authTime=" + this.authTime;
        res += "}";
        return res;
    }

}
