package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;

public class ApiLocation extends BserObject {

    private double ltd;
    private double lng;

    public ApiLocation(double ltd, double lng) {
        this.ltd = ltd;
        this.lng = lng;
    }

    public ApiLocation() {

    }

    public double getLtd() {
        return this.ltd;
    }

    public double getLng() {
        return this.lng;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.ltd = values.getDouble(1);
        this.lng = values.getDouble(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeDouble(1, this.ltd);
        writer.writeDouble(2, this.lng);
    }

    @Override
    public String toString() {
        String res = "struct Location{";
        res += "}";
        return res;
    }

}
